### ISSUE TITLE
[HTTPS] Certificate validation fails when using the default assigned domain

### ISSUE THREAD

**Issue by stilllman** [stilllman/freepybox#2]
According to @pdecat (see comments on [his PR](https://github.com/stilllman/freepybox/pull/1)), the validation of the default certificate provided by the Freebox when using the default domain does not work correctly, preventing the SSL handshake from succeeding.

**Comment by manatlan** [comment]
same trouble here

**Comment by pdecat** [comment]
Hi @manatlan, you should try the code in https://github.com/stilllman/freepybox/pull/3

**Comment by manatlan** [comment]
@pdecat ok, it's work for my ".freeboxos.fr" domain now, not for the fbxos one !
It's great like that !
thanks !

**Comment by manatlan** [comment]
BTW, i'm not sure to understand what I can do with the freebox in my hass ?!
now, I've got a "device_tracker.freebox_player" which seems to work : but what can I do with that ? (turn on/off ? change channels ?)
(need to ignore the discovery freebox to avoid bug for fbxos domain)

**Comment by stilllman** [comment]
@manatlan The Freebox hass component is just a device tracker for now. A device tracker is typically used as a presence detector, to know who is present in the home by tracking which devices are detected nearby. In this case, the Freebox component tells hass which devices are connected to the wifi, allowing you to know which smartphones are nearby for example.

If there is a need, a more complete component could be written, to provide access to other functions of the Freebox: turning wifi on/off, rebooting, getting the list of missed calls, etc. Note however that only the Freebox *server* can be interacted with, not the Freebox tv box, so you won't be able to swich tv channels and stuff like that.

**Comment by stilllman** [comment]
This issue has been fixed by PR #3.

**Comment by manatlan** [comment]
@stilllman thanks a lot ; it's clearer !
