### ISSUE TITLE
Authorization error : New application token request has been disabled not catched

### ISSUE THREAD

**Issue by SNoof85** [stilllman/freepybox#8]
In case the user did not ticked the new apps can ask for tokens there's no error thrown.
We should catch this as the API handles it.

**Comment by stilllman** [comment]
This issue also comes from the incorrect `raise_for_status` (see comments in #6 ). When removing it, the `new_apps_denied` error is correctly handled in `_get_app_token`, where it is returned initially (and not in `_get_authorization_status`).
